export const locations = [
    {
        city: "Dammam",
        address: "King Fahd Road, Al Shati District",
        phone: "+966 13 834 5678",
        hours: "Daily: 8:00 AM - 10:00 PM",
        lat: 26.4207,
        lng: 50.0888,
    },
    {
        city: "Khobar",
        address: "Prince Faisal Bin Fahd Road, Al Bandariyah",
        phone: "+966 13 898 1234",
        hours: "Daily: 8:00 AM - 10:00 PM",
        lat: 26.2895,
        lng: 50.208,
    },
    {
        city: "Jubail",
        address: "King Faisal Road, Industrial Area",
        phone: "+966 13 361 7890",
        hours: "Sat-Thu: 8:00 AM - 10:00 PM | Fri: 4:00 PM - 10:00 PM",
        lat: 27.0139,
        lng: 49.6583,
    },
    {
        city: "Dhahran",
        address: "King Saud Road, Near Mall of Dhahran",
        phone: "+966 13 864 2468",
        hours: "Daily: 8:00 AM - 11:00 PM",
        lat: 26.3025,
        lng: 50.1136,
    },
];


export const navLinks = [
    { name: "Home", path: "/" },
    { name: "Our Cars", path: "/cars" },
    { name: "About", path: "/about" },
    { name: "Contact", path: "/contact" },
    { name: "Locations", path: "/locations" },
];

export const cars = [
    {
        id: 1,
        model: "Toyota Corolla",
        type: "Sedan",
        color: "white",

        year: 2022,
        transmission: "Automatic",
        priceMonth: 2500,
        priceDay: 100,
        images: [
            "/cars/toyota-corolla-1.jpg",
            "/cars/toyota-corolla-2.jpg",
            "/cars/toyota-corolla-3.jpg",
        ],
    },
    {
        id: 2,
        model: "Toyota Yaris",
        type: "Hatchback",
        color: "gray",
        year: 2023,
        transmission: "Automatic",
        priceMonth: 2500,
        priceDay: 100,
        images: [
            "/cars/toyota-yaris-1.jpg",
            "/cars/toyota-yaris-2.jpg",
            "/cars/toyota-yaris-3.jpg",
        ],
    },
    {
        id: 3,
        model: "Chery Tiggo",
        type: "Compact SUV",
        color: "white",
        year: 2024,
        transmission: "Automatic",
        priceMonth: 3500,
        priceDay: 140,
        images: [
            "/cars/chery-tiggo-1.jpg",
            "/cars/chery-tiggo-2.jpg",
            "/cars/chery-tiggo-3.jpg",
        ],
    },
    {
        id: 4,
        model: "Hyundai Accent",
        type: "Sedan",
        color: "red",
        year: 2021,
        transmission: "Automatic",
        priceMonth: 2800,
        priceDay: 110,
        images: [
            "/cars/hyundai-accent-1.jpg",
            "/cars/hyundai-accent-2.jpg",
            "/cars/hyundai-accent-3.jpg",
        ],
    },
    {
        id: 5,
        model: "Kia Rio",
        type: "Sedan",
        color: "gray",
        year: 2024,
        transmission: "Automatic",
        priceMonth: 2700,
        priceDay: 105,
        images: [
            "/cars/kia-rio-1.jpg",
            "/cars/kia-rio-2.jpg",
            "/cars/kia-rio-3.jpg",
        ],
    },
    {
        id: 6,
        model: "Kia Sportage",
        type: "SUV",
        color: "white",
        year: 2025,
        transmission: "Automatic",
        priceMonth: 4500,
        priceDay: 180,
        images: [
            "/cars/kia-sportage-1.jpg",
            "/cars/kia-sportage-2.jpg",
            "/cars/kia-sportage-3.jpg",
        ],
    },
    {
        id: 7,
        model: "Nissan Sunny",
        type: "Sedan",
        color: "black",
        year: 2022,
        transmission: "Automatic",
        priceMonth: 2400,
        priceDay: 95,
        images: [],
    },
    {
        id: 8,
        model: "Honda Civic",
        type: "Sedan",
        color: "blue",
        year: 2023,
        transmission: "Automatic",
        priceMonth: 3200,
        priceDay: 130,
        images: [],
    },
    {
        id: 9,
        model: "Honda CR-V",
        type: "SUV",
        color: "silver",
        year: 2024,
        transmission: "Automatic",
        priceMonth: 4700,
        priceDay: 190,
        images: [],
    },
    {
        id: 10,
        model: "Chevrolet Aveo",
        type: "Hatchback",
        color: "white",
        year: 2021,
        transmission: "Automatic",
        priceMonth: 2200,
        priceDay: 90,
        images: [],
    },
    {
        id: 11,
        model: "Chevrolet Captiva",
        type: "SUV",
        color: "gray",
        year: 2023,
        transmission: "Automatic",
        priceMonth: 4000,
        priceDay: 160,
        images: [],
    },
    {
        id: 12,
        model: "Ford Focus",
        type: "Sedan",
        color: "blue",
        year: 2022,
        transmission: "Automatic",
        priceMonth: 2900,
        priceDay: 115,
        images: [],
    },
    {
        id: 13,
        model: "Ford Explorer",
        type: "SUV",
        color: "black",
        year: 2025,
        transmission: "Automatic",
        priceMonth: 5000,
        priceDay: 200,
        images: [],
    },
    {
        id: 14,
        model: "Mazda 3",
        type: "Sedan",
        color: "red",
        year: 2024,
        transmission: "Automatic",
        priceMonth: 3100,
        priceDay: 125,
        images: [],
    },
    {
        id: 15,
        model: "Mazda CX-5",
        type: "SUV",
        color: "white",
        year: 2023,
        transmission: "Automatic",
        priceMonth: 4300,
        priceDay: 170,
        images: [],
    },
    {
        id: 16,
        model: "Renault Logan",
        type: "Sedan",
        color: "silver",
        year: 2021,
        transmission: "Manual",
        priceMonth: 2000,
        priceDay: 80,
        images: [],
    },
    {
        id: 17,
        model: "Renault Duster",
        type: "SUV",
        color: "green",
        year: 2024,
        transmission: "Automatic",
        priceMonth: 3600,
        priceDay: 145,
        images: [],
    },
    {
        id: 18,
        model: "Suzuki Swift",
        type: "Hatchback",
        color: "red",
        year: 2022,
        transmission: "Automatic",
        priceMonth: 2300,
        priceDay: 90,
        images: [],
    },
    {
        id: 19,
        model: "Suzuki Vitara",
        type: "Compact SUV",
        color: "blue",
        year: 2023,
        transmission: "Automatic",
        priceMonth: 3400,
        priceDay: 135,
        images: [],
    },
    {
        id: 20,
        model: "Volkswagen Jetta",
        type: "Sedan",
        color: "white",
        year: 2023,
        transmission: "Automatic",
        priceMonth: 3300,
        priceDay: 135,
        images: [],
    },
    {
        id: 21,
        model: "Volkswagen Tiguan",
        type: "SUV",
        color: "gray",
        year: 2024,
        transmission: "Automatic",
        priceMonth: 4600,
        priceDay: 185,
        images: [],
    },
    {
        id: 22,
        model: "Peugeot 301",
        type: "Sedan",
        color: "black",
        year: 2022,
        transmission: "Manual",
        priceMonth: 2100,
        priceDay: 85,
        images: [],
    },
    {
        id: 23,
        model: "Peugeot 2008",
        type: "Crossover",
        color: "orange",
        year: 2023,
        transmission: "Automatic",
        priceMonth: 3700,
        priceDay: 150,
        images: [],
    },
    {
        id: 24,
        model: "Skoda Octavia",
        type: "Sedan",
        color: "blue",
        year: 2024,
        transmission: "Automatic",
        priceMonth: 3400,
        priceDay: 140,
        images: [],
    },
    {
        id: 25,
        model: "Skoda Kodiaq",
        type: "SUV",
        color: "white",
        year: 2025,
        transmission: "Automatic",
        priceMonth: 4800,
        priceDay: 195,
        images: [],
    },
];

export const carTypes = [
    { label: "Sedan", value: "sedan" },
    { label: "SUV", value: "suv" },
    { label: "Hatchback", value: "hatchback" },
    { label: "Compact SUV", value: "compact suv" },
    { label: "Crossover", value: "crossover" },
    { label: "Minivan", value: "minivan" },
    { label: "Pickup Truck", value: "pickup truck" },
    { label: "Luxury", value: "luxury" },
    { label: "Sports Car", value: "sports car" },
    { label: "Convertible", value: "convertible" },
];
export const carColors = [
    { label: "White", value: "white" },
    { label: "Gray", value: "gray" },
    { label: "Red", value: "red" },
    { label: "Black", value: "black" },
    { label: "Blue", value: "blue" },
    { label: "Silver", value: "silver" },
    { label: "Green", value: "green" },
    { label: "Orange", value: "orange" },
];
export const carModels = [
    { label: "Toyota", value: "toyota" },
    { label: "Chery", value: "chery" },
    { label: "Hyundai", value: "hyundai" },
    { label: "Kia", value: "kia" },
    { label: "Nissan", value: "nissan" },
    { label: "Honda", value: "honda" },
    { label: "Chevrolet", value: "chevrolet" },
    { label: "Ford", value: "ford" },
    { label: "Mazda", value: "mazda" },
    { label: "Renault", value: "renault" },
    { label: "Suzuki", value: "suzuki" },
    { label: "Volkswagen", value: "volkswagen" },
    { label: "Peugeot", value: "peugeot" },
    { label: "Skoda", value: "skoda" },
]
export const carYears = ["2021", "2022", "2023", "2024", "2025"];