import { useTranslations } from "next-intl";
import { CarMap } from "./types";

export const useLocations = () => {
    const t = useTranslations("Locations.cities")
    return [
        {
            city: t("dammam.name"),
            address: t("dammam.address"),
            phone: "+966 13 834 5678",
            hours: t("dammam.hours"),
            lat: 26.4207,
            lng: 50.0888,
        },
        {
            phone: "+966 13 898 1234",
            city: t("khobar.name"),
            address: t("khobar.address"),
            hours: t("khobar.hours"),
            lat: 26.2895,
            lng: 50.208,
        },
        {
            phone: "+966 13 361 7890",
            city: t("jubail.name"),
            address: t("jubail.address"),
            hours: t("jubail.hours"),
            lat: 27.0139,
            lng: 49.6583,
        },
        {
            phone: "+966 13 864 2468",
            city: t("dhahran.name"),
            address: t("dhahran.address"),
            hours: t("dhahran.hours"),
            lat: 26.3025,
            lng: 50.1136,
        },
    ];
}

export const useNavLinks = () => {
    const t = useTranslations('Nav');

    return [
        { name: t('home'), path: '/' },
        { name: t('ourCars'), path: '/cars' },
        { name: t('about'), path: '/about' },
        { name: t('contact'), path: '/contact' },
        { name: t('locations'), path: '/locations' },
    ];
};

export const cars: CarMap[] = [
    {
        id: "1",
        model: "Toyota Corolla",
        year: 2022,
        type: "Sedan",
        transmission: "Automatic",
        priceMonth: 2500,
        priceDay: 100,
        availableColors: ["white", "black", "silver", "gray"],
        images: {
            white: [
                "/cars/toyota-corolla-1.jpg",
                "/cars/toyota-corolla-2.jpg",
                "/cars/toyota-corolla-3.jpg",
            ],
            black: [],
            silver: [],
            gray: [],
        },
    },
    {
        id: "2",
        model: "Toyota Yaris",
        year: 2023,
        type: "Hatchback",
        transmission: "Automatic",
        priceMonth: 2500,
        priceDay: 100,
        availableColors: ["gray", "red", "blue", "white"],
        images: {
            gray: [
                "/cars/toyota-yaris-1.jpg",
                "/cars/toyota-yaris-2.jpg",
                "/cars/toyota-yaris-3.jpg",
            ],
            red: [],
            blue: [],
            white: [],
        },
    },
    {
        id: "27",
        model: "Toyota Yaris",
        year: 2021,
        type: "Hatchback",
        transmission: "Automatic",
        priceMonth: 2800,
        priceDay: 100,
        availableColors: ["silver", "red", "blue", "white"],
        images: {
            silver: [
                "/cars/toyota-yaris-1.jpg",
                "/cars/toyota-yaris-2.jpg",
                "/cars/toyota-yaris-3.jpg",
            ],
            red: [],
            blue: [],
            white: [],
        },
    },
    {
        id: "3",
        model: "Chery Tiggo",
        year: 2024,
        type: "Compact SUV",
        transmission: "Automatic",
        priceMonth: 3500,
        priceDay: 140,
        availableColors: ["white", "black", "gray"],
        images: {
            white: [
                "/cars/chery-tiggo-1.jpg",
                "/cars/chery-tiggo-2.jpg",
                "/cars/chery-tiggo-3.jpg",
            ],
            black: [],
            gray: [],
        },
    },
    {
        id: "4",
        model: "Hyundai Accent",
        year: 2021,
        type: "Sedan",
        transmission: "Automatic",
        priceMonth: 2800,
        priceDay: 110,
        availableColors: ["red", "silver", "gray", "white"],
        images: {
            red: [
                "/cars/hyundai-accent-1.jpg",
                "/cars/hyundai-accent-2.jpg",
                "/cars/hyundai-accent-3.jpg",
            ],
            silver: [],
            gray: [],
            white: [],
        },
    },
    {
        id: "5",
        model: "Kia Rio",
        year: 2024,
        type: "Sedan",
        transmission: "Automatic",
        priceMonth: 2700,
        priceDay: 105,
        availableColors: ["gray", "blue", "white"],
        images: {
            gray: [
                "/cars/kia-rio-1.jpg",
                "/cars/kia-rio-2.jpg",
                "/cars/kia-rio-3.jpg",
            ],
            blue: [],
            white: [],
        },
    },
    {
        id: "6",
        model: "Kia Sportage",
        year: 2025,
        type: "SUV",
        transmission: "Automatic",
        priceMonth: 4500,
        priceDay: 180,
        availableColors: ["white", "black", "silver", "dark green"],
        images: {
            white: [
                "/cars/kia-sportage-1.jpg",
                "/cars/kia-sportage-2.jpg",
                "/cars/kia-sportage-3.jpg",
            ],
            black: [],
            silver: [],
            "dark green": [],
        },
    },
    {
        id: "7",
        model: "Nissan Sunny",
        year: 2022,
        type: "Sedan",
        transmission: "Automatic",
        priceMonth: 2400,
        priceDay: 95,
        availableColors: ["black", "silver", "gray", "white"],
        images: {
            black: [],
            silver: [],
            gray: [],
            white: [],
        },
    },
    {
        id: "8",
        model: "Honda Civic",
        year: 2023,
        type: "Sedan",
        transmission: "Automatic",
        priceMonth: 3200,
        priceDay: 130,
        availableColors: ["blue", "black", "gray", "red"],
        images: {
            blue: [],
            black: [],
            gray: [],
            red: [],
        },
    },
    {
        id: "9",
        model: "Honda CR-V",
        year: 2024,
        type: "SUV",
        transmission: "Automatic",
        priceMonth: 4700,
        priceDay: 190,
        availableColors: ["silver", "white", "black", "dark blue"],
        images: {
            silver: [],
            white: [],
            black: [],
            "dark blue": [],
        },
    },
    {
        id: "10",
        model: "Chevrolet Aveo",
        year: 2021,
        type: "Hatchback",
        transmission: "Automatic",
        priceMonth: 2200,
        priceDay: 90,
        availableColors: ["white", "red", "blue"],
        images: {
            white: [],
            red: [],
            blue: [],
        },
    },
    {
        id: "11",
        model: "Chevrolet Captiva",
        year: 2023,
        type: "SUV",
        transmission: "Automatic",
        priceMonth: 4000,
        priceDay: 160,
        availableColors: ["gray", "black", "blue", "white"],
        images: {
            gray: [],
            black: [],
            blue: [],
            white: [],
        },
    },
    {
        id: "12",
        model: "Ford Focus",
        year: 2022,
        type: "Sedan",
        transmission: "Automatic",
        priceMonth: 2900,
        priceDay: 115,
        availableColors: ["blue", "white", "black", "silver"],
        images: {
            blue: [],
            white: [],
            black: [],
            silver: [],
        },
    },
    {
        id: "13",
        model: "Ford Explorer",
        year: 2025,
        type: "SUV",
        transmission: "Automatic",
        priceMonth: 5000,
        priceDay: 200,
        availableColors: ["black", "gray", "blue"],
        images: {
            black: [],
            gray: [],
            blue: [],
        },
    },
    {
        id: "14",
        model: "Mazda 3",
        year: 2024,
        type: "Sedan",
        transmission: "Automatic",
        priceMonth: 3100,
        priceDay: 125,
        availableColors: ["red", "white", "gray", "black"],
        images: {
            red: [],
            white: [],
            gray: [],
            black: [],
        },
    },
    {
        id: "15",
        model: "Mazda CX-5",
        year: 2023,
        type: "SUV",
        transmission: "Automatic",
        priceMonth: 4300,
        priceDay: 170,
        availableColors: ["white", "black", "blue", "gray"],
        images: {
            white: [],
            black: [],
            blue: [],
            gray: [],
        },
    },
    {
        id: "16",
        model: "Renault Logan",
        year: 2021,
        type: "Sedan",
        transmission: "Manual",
        priceMonth: 2000,
        priceDay: 80,
        availableColors: ["silver", "white", "black"],
        images: {
            silver: [],
            white: [],
            black: [],
        },
    },
    {
        id: "17",
        model: "Renault Duster",
        year: 2024,
        type: "SUV",
        transmission: "Automatic",
        priceMonth: 3600,
        priceDay: 145,
        availableColors: ["green", "gray", "white", "black"],
        images: {
            green: [],
            gray: [],
            white: [],
            black: [],
        },
    },
    {
        id: "18",
        model: "Suzuki Swift",
        year: 2022,
        type: "Hatchback",
        transmission: "Automatic",
        priceMonth: 2300,
        priceDay: 90,
        availableColors: ["red", "white", "blue", "gray"],
        images: {
            red: [],
            white: [],
            blue: [],
            gray: [],
        },
    },
    {
        id: "19",
        model: "Suzuki Vitara",
        year: 2023,
        type: "Compact SUV",
        transmission: "Automatic",
        priceMonth: 3400,
        priceDay: 135,
        availableColors: ["blue", "silver", "white", "black"],
        images: {
            blue: [],
            silver: [],
            white: [],
            black: [],
        },
    },
    {
        id: "20",
        model: "Volkswagen Jetta",
        year: 2023,
        type: "Sedan",
        transmission: "Automatic",
        priceMonth: 3300,
        priceDay: 135,
        availableColors: ["white", "black", "red", "gray"],
        images: {
            white: [],
            black: [],
            red: [],
            gray: [],
        },
    },

    {
        id: "21",
        model: "Volkswagen Tiguan",
        year: 2024,
        type: "SUV",
        transmission: "Automatic",
        priceMonth: 4600,
        priceDay: 185,
        availableColors: ["gray", "black", "white", "silver"],
        images: {
            gray: [],
            black: [],
            white: [],
            silver: [],
        },
    },
    {
        id: "22",
        model: "Peugeot 301",
        year: 2022,
        type: "Sedan",
        transmission: "Manual",
        priceMonth: 2100,
        priceDay: 85,
        availableColors: ["black", "silver", "white"],
        images: {
            black: [],
            silver: [],
            white: [],
        },
    },
    {
        id: "23",
        model: "Peugeot 2008",
        year: 2023,
        type: "Crossover",
        transmission: "Automatic",
        priceMonth: 3700,
        priceDay: 150,
        availableColors: ["orange", "white", "gray", "blue"],
        images: {
            orange: [],
            white: [],
            gray: [],
            blue: [],
        },
    },
    {
        id: "24",
        model: "Skoda Octavia",
        year: 2024,
        type: "Sedan",
        transmission: "Automatic",
        priceMonth: 3400,
        priceDay: 140,
        availableColors: ["blue", "gray", "white", "black"],
        images: {
            blue: [],
            gray: [],
            white: [],
            black: [],
        },
    },
    {
        id: "25",
        model: "Skoda Kodiaq",
        year: 2025,
        type: "SUV",
        transmission: "Automatic",
        priceMonth: 4800,
        priceDay: 195,
        availableColors: ["white", "black", "gray", "silver"],
        images: {
            white: [],
            black: [],
            gray: [],
            silver: [],
        },
    },
];


export const carTypes = [
    "Sedan",
    "SUV",
    "Hatchback",
    "Compact SUV",
    "Crossover",
    "Minivan",
    "Pickup Truck",
    "Luxury",
    "Sports Car",
    "Convertible"
];
export const carColors = [
    "black",
    "white",
    "gray",
    "silver",
    "red",
    "blue",
    "green",
    "yellow",
    "orange",
    "brown",
    "beige",
    "gold",
    "purple",
    "pink"
];
export const carModels = [
    "Toyota",
    "Chery",
    "Hyundai",
    "Kia",
    "Nissan",
    "Honda",
    "Chevrolet",
    "Ford",
    "Mazda",
    "Renault",
    "Suzuki",
    "Volkswagen",
    "Peugeot",
    "Skoda",
]
export const carYears = ["2021", "2022", "2023", "2024", "2025"];